# Generated by Django 3.2.9 on 2021-11-16 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightbs',
            old_name='title',
            new_name='Flight_Name',
        ),
        migrations.RemoveField(
            model_name='flightbs',
            name='description',
        ),
        migrations.AddField(
            model_name='flightbs',
            name='passenger_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
