# Generated by Django 3.2.9 on 2021-11-16 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211116_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbs',
            name='Destination',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
