# Generated by Django 3.2.9 on 2021-11-16 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_flightbs_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbs',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
